project_id = "xzcrzqyhubrsndopnzxj"

[functions.send-support-message]
verify_jwt = false

[functions.process-kakaopay-payment]
verify_jwt = true

[functions.kakaopay-callback]
verify_jwt = false

[functions.send-subscription-confirmation]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.generate-ai-plan]
verify_jwt = true

[functions.send-reminders]
verify_jwt = false

[functions.update-achievements]
verify_jwt = false
