project_id = "xzcrzqyhubrsndopnzxj"

[functions.send-support-message]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.activate-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-ai-plan]
verify_jwt = true

[functions.send-reminders]
verify_jwt = false

[functions.update-achievements]
verify_jwt = true

[functions.create-recurring-price]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-premium-email]
verify_jwt = false

[functions.send-refund-email]
verify_jwt = false

[functions.handle-subscription-cancel]
verify_jwt = true
