-- Insert 50+ упражнений (exercises) с animation_url
INSERT INTO public.exercises (name, description, duration, category, is_premium, animation_url) VALUES
-- Дыхательные упражнения (breathing)
('Дыхание 4-7-8', 'Вдох через нос 4 секунды, задержка 7 секунд, выдох через рот 8 секунд. Снимает стресс и тягу.', 240, 'breathing', false, 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWtyZGlsOHNlbGk3YW5lbTN6bGl0aGdyeWVlcnhqMmN6bGFwZXJzdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l0HlPwMAzh13pcZ20/giphy.gif'),
('Диафрагмальное дыхание', 'Лягте на спину, положите руку на живот. Вдыхайте, надувая живот, выдыхайте медленно.', 300, 'breathing', false, 'https://media.giphy.com/media/3o7TKS6AWINqbg3FV6/giphy.gif'),
('Квадратное дыхание', 'Вдох 4 счета, задержка 4, выдох 4, задержка 4. Повторяйте 5 минут.', 300, 'breathing', false, 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWhyZGtjYzh0cWxjNWhhbGtyYm95YmQ5aGF5Y2JpeTRnenV5YjZ4ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/26gR0hw5iH5Z4uT4Y/giphy.gif'),
('Дыхание Вим Хофа', '30 быстрых глубоких вдохов, затем задержка на максимум. Повторить 3 раза.', 360, 'breathing', true, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Попеременное дыхание', 'Закройте правую ноздрю, вдохните левой. Закройте левую, выдохните правой. Чередуйте 5 минут.', 300, 'breathing', false, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Дыхание огня', 'Короткие резкие выдохи носом, живот втягивается. 1 минута.', 60, 'breathing', true, 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif'),
('Медленное дыхание', 'Вдох 5 секунд, выдох 5 секунд. Синхронизируйте с сердечным ритмом.', 360, 'breathing', false, 'https://media.giphy.com/media/3o7TKS6AWINqbg3FV6/giphy.gif'),
('Дыхание с визуализацией', 'Вдыхайте чистый воздух (представляйте свет), выдыхайте токсины (темный дым).', 300, 'breathing', true, 'https://media.giphy.com/media/26gR0hw5iH5Z4uT4Y/giphy.gif'),
('Рёберное дыхание', 'Положите руки на рёбра. Вдыхайте, расширяя грудную клетку в стороны.', 240, 'breathing', false, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Дыхание для сна', 'Лёжа в кровати, делайте 10 циклов 4-7-8. Помогает заснуть без сигарет.', 300, 'breathing', false, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),

-- Физические упражнения (physical)
('Приседания классические', 'Ноги на ширине плеч, приседайте до параллели. 3 подхода по 15 раз.', 180, 'physical', false, 'https://media.giphy.com/media/ZXBHzDKH51U8oi7Oqu/giphy.gif'),
('Отжимания от пола', 'Руки шире плеч, опускайтесь до касания грудью пола. 3 подхода по 10 раз.', 180, 'physical', false, 'https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif'),
('Планка статическая', 'Держите тело прямо на локтях и носках. Начните с 30 секунд, увеличивайте.', 60, 'physical', false, 'https://media.giphy.com/media/3o7TKqj3kQyjVJBQS4/giphy.gif'),
('Берпи', 'Присед-отжимание-прыжок. 10 повторений для взрыва эндорфинов.', 120, 'physical', true, 'https://media.giphy.com/media/l0HlRnAWXxn0MhKLK/giphy.gif'),
('Выпады на каждую ногу', 'Шаг вперед, колено под 90 градусов. 12 раз на каждую ногу.', 120, 'physical', false, 'https://media.giphy.com/media/3o7TKH2bD8zWKnYfQY/giphy.gif'),
('Прыжки со скакалкой', 'Прыгайте 1 минуту, отдых 30 секунд. 5 подходов.', 360, 'physical', true, 'https://media.giphy.com/media/l0HlDHQEiIdY3kxlm/giphy.gif'),
('Подъемы на носки', 'Встаньте на ступеньку, поднимайтесь на носках. 20 раз.', 90, 'physical', false, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Скручивания на пресс', 'Лёжа на спине, руки за головой. Подъем верхней части тела. 20 раз.', 120, 'physical', false, 'https://media.giphy.com/media/3o7TKvdN0RmFEDGSL6/giphy.gif'),
('Боковая планка', 'Опора на один локоть, держите 30 секунд. Меняйте стороны.', 120, 'physical', true, 'https://media.giphy.com/media/3o7TKH2bD8zWKnYfQY/giphy.gif'),
('Велосипед лёжа', 'Лёжа на спине, имитируйте кручение педалей. 2 минуты.', 120, 'physical', false, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Прыжки в стороны', 'Прыгайте влево-вправо через линию. 30 секунд интенсивно.', 60, 'physical', false, 'https://media.giphy.com/media/ZXBHzDKH51U8oi7Oqu/giphy.gif'),
('Мостик для ягодиц', 'Лёжа на спине, поднимайте таз вверх. 15 повторений.', 90, 'physical', false, 'https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif'),
('Подтягивания (или негативы)', 'Если есть турник - подтягивайтесь. Начните с негативных (медленный спуск).', 180, 'physical', true, 'https://media.giphy.com/media/3o7TKqj3kQyjVJBQS4/giphy.gif'),
('Растяжка задней поверхности', 'Сидя, тянитесь к носкам. Держите 30 секунд на каждую ногу.', 120, 'physical', false, 'https://media.giphy.com/media/l0HlRnAWXxn0MhKLK/giphy.gif'),
('Динамическая планка', 'Из планки на руках переходите на локти и обратно. 10 раз.', 90, 'physical', true, 'https://media.giphy.com/media/3o7TKH2bD8zWKnYfQY/giphy.gif'),
('Удары ногами назад', 'На четвереньках, поднимайте ногу назад-вверх. 15 раз на каждую.', 120, 'physical', false, 'https://media.giphy.com/media/l0HlDHQEiIdY3kxlm/giphy.gif'),
('Махи руками круговые', 'Вращайте руками назад, затем вперед. По 30 секунд.', 60, 'physical', false, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Альпинист', 'В планке подтягивайте колени к груди поочередно. 30 секунд быстро.', 60, 'physical', true, 'https://media.giphy.com/media/3o7TKvdN0RmFEDGSL6/giphy.gif'),
('Касания носков стоя', 'Наклоняйтесь, касаясь правой рукой левого носка, затем наоборот. 20 раз.', 90, 'physical', false, 'https://media.giphy.com/media/3o7TKH2bD8zWKnYfQY/giphy.gif'),
('Прыжки с разведением', 'Jumping jacks - прыжки с разведением рук и ног. 50 раз.', 90, 'physical', false, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),

-- Медитация (meditation)
('Сканирование тела', 'Лягте удобно. Мысленно сканируйте каждую часть тела от пальцев ног до макушки.', 600, 'meditation', true, 'https://media.giphy.com/media/3o7TKS6AWINqbg3FV6/giphy.gif'),
('Медитация на дыхание', 'Сидите прямо, фокусируйтесь только на дыхании. Когда отвлекаетесь - возвращайтесь.', 600, 'meditation', false, 'https://media.giphy.com/media/26gR0hw5iH5Z4uT4Y/giphy.gif'),
('Визуализация океана', 'Представьте, что сидите на берегу. Волны уносят вашу тягу к курению.', 420, 'meditation', true, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Медитация любящей доброты', 'Посылайте добрые пожелания себе, близким, всем людям. Начните с "Пусть я буду здоров".', 480, 'meditation', true, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Наблюдение за мыслями', 'Сидите тихо, наблюдайте мысли как облака. Не цепляйтесь, пусть проходят.', 480, 'meditation', false, 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif'),
('Медитация на звук', 'Закройте глаза, слушайте все звуки вокруг, не оценивая их.', 360, 'meditation', false, 'https://media.giphy.com/media/3o7TKS6AWINqbg3FV6/giphy.gif'),
('Медитация на точку', 'Смотрите на точку на стене, не моргая. Ум успокаивается.', 180, 'meditation', false, 'https://media.giphy.com/media/26gR0hw5iH5Z4uT4Y/giphy.gif'),
('Прогрессивная релаксация', 'Напрягайте и расслабляйте каждую группу мышц поочередно.', 480, 'meditation', true, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Медитация ходьбы', 'Ходите медленно, осознавая каждый шаг. Пятка-носок-пятка-носок.', 600, 'meditation', true, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Медитация благодарности', 'Вспомните 10 вещей, за которые благодарны. Почувствуйте благодарность в груди.', 360, 'meditation', false, 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif'),
('Йога-нидра', 'Управляемая релаксация всего тела в положении лежа. Как глубокий сон наяву.', 900, 'meditation', true, 'https://media.giphy.com/media/3o7TKS6AWINqbg3FV6/giphy.gif'),
('Медитация на цвет', 'Представьте исцеляющий зеленый свет, наполняющий ваше тело.', 360, 'meditation', true, 'https://media.giphy.com/media/26gR0hw5iH5Z4uT4Y/giphy.gif'),
('Осознанное слушание', 'Включите спокойную музыку, слушайте каждый инструмент отдельно.', 480, 'meditation', false, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Медитация на свечу', 'Смотрите на пламя свечи, не моргая. Затем закройте глаза и видьте отпечаток.', 300, 'meditation', false, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Мантра-медитация', 'Повторяйте про себя "Ом" или "Я здоров" 108 раз.', 480, 'meditation', true, 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif'),
('Медитация прощения', 'Простите себя за прошлое курение. Отпустите вину и стыд.', 420, 'meditation', true, 'https://media.giphy.com/media/3o7TKS6AWINqbg3FV6/giphy.gif'),
('Дзадзен', 'Сидите в позе лотоса или полулотоса, спина прямая. Просто будьте 10 минут.', 600, 'meditation', true, 'https://media.giphy.com/media/26gR0hw5iH5Z4uT4Y/giphy.gif'),
('Медитация на сердце', 'Положите руку на сердце, чувствуйте его биение. Посылайте любовь себе.', 360, 'meditation', false, 'https://media.giphy.com/media/l0HlTy9x8FZo0XO1i/giphy.gif'),
('Випассана для новичков', 'Наблюдайте ощущения в теле без реакции. Покалывание, тепло, холод - просто замечайте.', 600, 'meditation', true, 'https://media.giphy.com/media/3o6ZsX1XqxWNQMgIz6/giphy.gif'),
('Утренняя медитация', 'Сразу после пробуждения сидите 5 минут, настраивая день без сигарет.', 300, 'meditation', false, 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif');
